### ISSUE TITLE
Shorten links, prompts download dialogue instead the usual online preview

### ISSUE THREAD

**Issue by enekux** [Fmstrat/shorten#12]
Hello there,

when I try to access to a link created by shorten it prompts me with the download dialogue and not the usual online preview of the shared item, as the default share links do.

Is this behaviour normal?

Thank you.

**Comment by Fmstrat** [comment]
It is for now, as that's what creates the privacy in the intermediate proxy. There is already a request to create independent short links for each: https://github.com/Fmstrat/shorten/issues/5

I'll be addressing the enhancements here once ownNote is securely into it's 1.0 stage. Thanks.
