### ISSUE TITLE
Whenever trying to configure the app I am logged out, nothing is saved...

### ISSUE THREAD

**Issue by arkascha** [Fmstrat/shorten#15]
I installed the app in an owncloud-8.0.x installation that works fine otherwise. 
I go to the administration page, switch to the internal shortener and enter the base URL as described (https://some-domain-I-own/s) an leave the focus of the input field. Whatever I do next I am requested to re-login and the settings have not been saved. 
No entries appear in the log file though...

**Comment by gdupuis** [comment]
Hello,
I have the same issue/behavior with owncloud 8.1.3 and Shorten 0.0.11.

In the console, I can see this message : 
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead

Thanks for your help!

**Comment by Fmstrat** [comment]
What OS and webserver is OC running on?

**Comment by gdupuis** [comment]
I'm running Ubuntu 14.04.3 LTS with apache 2.4.7-1ubuntu4.6.

**Comment by arkascha** [comment]
An older openSUSE with apache2-2.2.29, php5-5.6.4, owncloud-8.0.x

**Comment by Fmstrat** [comment]
This was an error with CORS that I think I've figured out. Latest v0.0.12 is on the app store now.
