### ISSUE TITLE
Doesn't seem to work on ownCloud 8.2 w/ yourls 1.7

### ISSUE THREAD

**Issue by sndtnd** [Fmstrat/shorten#18]
shorten 0.0.13
yourls 1.7 installed at https://domain.tld/s/
owncloud 8.2 installed at https://domain.tld/owncloud/

Changed admin menu option to 'YOURLS,' entered https://domain.tld/s as url without trailing slash. Entered the secret signature token in 2nd field.

When I share a file, the share link is the normal https://domain.tld/owncloud/index.php/s/blahblah.  Nothing in logs, no shorturl created in yourls.

**Comment by oksiquatzel** [comment]
same problem on my site.
I tried yourls installation and internal filtering with copying and changing index.php 
but both does not show the short link
owncloud 8.2 
yourls 1.7
shorten 0.0.13

**Comment by JSoko** [comment]
Yourls worked fine under oc 8.1.3

After upgraded to 8.2.0 same issue as above, no shortening :-(

**Comment by josepmendoza** [comment]
Same here, oc 8.2 update no works.

**Comment by cs39** [comment]
I am also having issues after upgrading to oc 8.2. Shorten is not working so I tried a fresh install of oc 8.2 and latest shorten as well... same result.
owncloud 8.2
yourls 1.7
shorten 0.0.13

**Comment by McCovican** [comment]
Internal shortner also stopped working after the update to 8.2 for me.

**Comment by Fmstrat** [comment]
Fixed in .14 about to release.

**Comment by JSoko** [comment]
Works again with yourls and oc 8.2.

Thank You! : :+1:
