### ISSUE TITLE
No save button

### ISSUE THREAD

**Issue by dieseitenwerkstatt** [Fmstrat/shorten#2]
Cannot see a save button in owncloud admin area and automatic save isn't working when leaving field. i'm using internal shortener

**Comment by Fmstrat** [comment]
What browser, browser version, and owncloud version are you using? Leaving the field is working for me on all my test systems so I just need to attempt to replicate. Have you tried another browser?

**Comment by dieseitenwerkstatt** [comment]
ownCloud 7.0.4
Google Chrome 39.0.2171.95 m
Firefox Developer Edition 36.0a2
Internet Explorer 11.0.9600.17498 Update Version 11.0.15

**Comment by Fmstrat** [comment]
I cannot seem to replicate this. Can you check the Firefox console (or Firebug console if you have it) and let me know if any JS errors are popping up? I'm wondering if there is a JS conflict with another App you have installed.

**Comment by lo-man** [comment]
here is exact the same behaviour. I've disabled all other apps in my test environment but without success. Firefox, chrome and IE are all in the newest version. Owncloud 7.04. Quite the same like Puckmeister.

**Comment by beduine** [comment]
Try replacing checkAppEnabled('ownnote') with checkAppEnabled('shorten') in code.php and ajax/*.php - this will solve the issue. It also explains why it works at your place ;)

**Comment by Fmstrat** [comment]
Doh! That's what I get for developing multiple apps at once. Fix coming shortly.

**Comment by Fmstrat** [comment]
0.0.7 is out and addresses this issue. Marking closed. Thanks everyone!

**Comment by kugel-** [comment]
I face this issue on 0.11 and current master.

**Comment by Fmstrat** [comment]
Sorry for the delay. Notifications got turned off somehow and I've been focusing on ownNote. Can you look at your JS console in something like Firebug and let me know if any JS issues are occurring?

**Comment by Fmstrat** [comment]
I believe this was related to the CORS error already fixed. Please update to v0.0.12.
