### ISSUE TITLE
Call to undefined function startsWith() in Path\s\index.php on line 31

### ISSUE THREAD

**Issue by trockenasche** [Fmstrat/shorten#4]
just installed this addon and in OC I get the short url. But opening this short url i'm getting this error:
( ! ) Fatal error: Call to undefined function startsWith() in path\s\index.php on line 31
Call Stack
# Time Memory  Function    Location
1   0.0006  146432  {main}( )   ..\index.php:0

**Comment by noisem** [comment]
I've copied it from file ajax/makeurl.php, but still doesn't work. i.e. there is no any error on web server side but shared file is not downloaded

**Comment by noisem** [comment]
until correction I'm using just location header:

``` javascript
<?php

#
# Enter your owncloud URL below with no trailing slash
# Ex. "https://mydomain.ext/owncloud"
#
$owncloud_url = "https://mydomain.ext/owncloud";

#
# Set enabled to true when you are ready to use the application
#
#$enabled = true;
$enabled = true;


function validateCode($string) {
    if(preg_match("/^[\w]+$/", $string)) {
        return true;
    } else {
        return false;
    }
}

if ($enabled) {
    $inurl = $_SERVER["REQUEST_URI"];
    $code = substr($inurl, strpos($inurl, "?") + 1);    
    if (validateCode($code)) {
        $url = $owncloud_url."/index.php/apps/shorten/code.php?code=".$code;
        header("Location: " . $url);
    } else {
        echo "Invalid link.";
    }
}

?>

```

**Comment by trockenasche** [comment]
if it's working, you should make a pull request.

**Comment by noisem** [comment]
It's working but I've just deleted some code and used standard php redirect (Location header). It seems that the developer had some ideas like to not even to display owncloud web site, but to download within the same short link. i.e. the user don't receive at all full link. This is good from security point of view but on other hand, some time I want to share for example a folder with images which the receiver of the link should not download by default but slide in the browser and download only images he like. So, I would prefer to have a choice when to share short link with default download action or just redirect to full link.

**Comment by Fmstrat** [comment]
A proper fix is this in commit: https://github.com/Fmstrat/shorten/commit/97a6ab9d1c89cd1db573de9790e7ded9febb338f and will be rolled into the next release.

If you are looking for an alternative shortener that does not fully hide the source URL, please post a separate issue with a title related to that, and I will mark it and add it to the enhancement requests. Thanks.

**Comment by noisem** [comment]
Hi  Fmstrat, for me just adding of startsWith it's not working in default installation (the file is not downloaded). but works when commenting "$url = $url."&download";"
maybe it's matter of web server/php configuration ?
