### ISSUE TITLE
Change needed

### ISSUE THREAD

**Issue by drsbaitso** [Fmstrat/shorten#8]
Line 47 in script.js has to be changed... the /owncloud borks it when your cloud isn't at that url obvs.

```
$.post("/owncloud/index.php/apps/shorten/makeurl", { curUrl: curUrl }, function (data) {
```

should be

```
$.post("/index.php/apps/shorten/makeurl", { curUrl: curUrl }, function (data) {
```

**Comment by Fmstrat** [comment]
Doh, meant to change that to grab the URL from the owncloud API. I will update shortly.

**Comment by Fmstrat** [comment]
Updated in master to support any folder structure, will be released in a few moments.
