### ISSUE TITLE
Feature request - YOURLS support

### ISSUE THREAD

**Issue by MrBlackRocket** [Fmstrat/shorten#9]
Please add [YOURLS](https://github.com/YOURLS/YOURLS) support

**Comment by cs39** [comment]
I Agree! This app would be a perfect addition to the ownCloud family if it had YOURLS support. YOURLS has an API just as goo.gl does. Please add YOURLS support.

**Comment by Fmstrat** [comment]
Added. Will be in v.13. https://github.com/Fmstrat/shorten/commit/63b4d1d3701bd06cc9966c33689fb8f4db8dd0f3
